<?php

namespace DiamondRecruiter\RecruiterBundle\Repository;

/**
 * CandidateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidateRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSearch($search)
    {
        $queryBuilder = $this->createQueryBuilder('candidate');
        $queryBuilder
            ->where('candidate.fullname LIKE :search')
            ->orWhere('candidate.email LIKE :search1')
            ->setParameter('search', '%'.$search.'%')
            ->setParameter('search1', '%'.$search.'%')
        ;
        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }
}
