<?php

namespace DiamondRecruiter\RecruiterBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSearch($search)
    {
        $queryBuilder = $this->createQueryBuilder('contact');
        $queryBuilder
            ->where('contact.name LIKE :search1')
            ->orWhere('contact.email LIKE :search2')
            ->setParameter('search1', '%'.$search.'%')
            ->setParameter('search2', '%'.$search.'%')
        ;
        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }
}
