<?php

namespace DiamondRecruiter\RecruiterBundle\Repository;

/**
 * SubmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubmissionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSearch($search)
    {
        $queryBuilder = $this->createQueryBuilder('submission');
        $queryBuilder
            ->where('submission.title LIKE :search1')
            ->setParameter('search1', '%'.$search.'%')
        ;
        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }
}
