<?php

namespace DiamondRecruiter\RecruiterBundle\Repository;

/**
 * VacancyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacancyRepository extends \Doctrine\ORM\EntityRepository
{
    public function getReedVacancy($id)
    {
        $queryBuilder = $this->createQueryBuilder('vacancy');
        $queryBuilder
            ->where('reed_job_id = :reed_id')
            ->setParameter('reed_id', $id)
        ;
        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }

    public function getSearch($search)
    {
        $queryBuilder = $this->createQueryBuilder('vacancy');
        $queryBuilder
            ->where('vacancy.title LIKE :search1')
            ->orWhere('vacancy.jobDescription LIKE :search2')
            ->setParameter('search1', '%'.$search.'%')
            ->setParameter('search2', '%'.$search.'%')
        ;
        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }



}
