<?php

namespace DiamondRecruiter\UserBundle\Repository;

/**
 * TenantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNotTenanted()
    {
        $queryBuilder = $this->createQueryBuilder('user');
        $queryBuilder
            ->orderBy('user.id', 'DESC')
            ->where('user.tenant is NULL')
        ;
        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }
}